spring:
  jackson:
    serialization:
      indent-output: true
security:
  oauth2:
    client:
      clientId: <YOUR CLIENT ID>
      clientSecret: <YOUR CLIENT SECRET>
      accessTokenUri: https://sandbox.bluebutton.cms.gov/v1/o/token/
      userAuthorizationUri: https://sandbox.bluebutton.cms.gov/v1/o/authorize/
      tokenName: access_token
      authenticationScheme: header
      clientAuthenticationScheme: header
      scope: profile patient/Coverage.read patient/Patient.read patient/ExplanationOfBenefit.read
    resource:
      userInfoUri: https://sandbox.bluebutton.cms.gov/v1/fhir/Patient/
...